version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    networks:
      - ollama_network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./server.crt:/etc/ssl/certs/server.crt
      - ./server.key:/etc/ssl/private/server.key
      - ./ca.crt:/etc/ssl/certs/ca.crt
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    networks:
      - ollama_network

networks:
  ollama_network:
    driver: bridge