services:
  nginx:
    container_name: ollama-tls-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    networks:
      - ollama_network
    volumes:
      - ./server.crt:/etc/ssl/certs/server.crt
      - ./server.key:/etc/ssl/private/server.key
      - ./ca.crt:/etc/ssl/certs/ca.crt
    depends_on:
      - ollama

  ollama:
    container_name: ollama-tls-ollama
    build:
      context: ./ollama
      dockerfile: Dockerfile
      args:
        MODEL: granite3.1-moe:1b
    networks:
      - ollama_network

networks:
  ollama_network:
    driver: bridge